<html>
<head>
<title>TestNG:  Zyto Automation Test</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Zyto Automation Test</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>23/3/0</td>
</tr><tr>
<td>Started on:</td><td>Sun Jul 26 00:21:28 IST 2020</td>
</tr>
<tr><td>Total time:</td><td>1594 seconds (1594452 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED CONFIGURATIONS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.zyto.test.base.ZytoBaseTest.setUp()'><b>setUp</b><br>Test class: com.zyto.test.base.ZytoBaseTest</td>
<td><div><pre>org.testng.TestNGException: 
Parameter &apos;browser&apos; is required by BeforeTest on method setUp but has not been marked @Optional or defined
in D:\New folder\ZytoTestAutomation\testng.xml
... Removed 21 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace423583818", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace423583818'><pre>org.testng.TestNGException: 
Parameter &apos;browser&apos; is required by BeforeTest on method setUp but has not been marked @Optional or defined
in D:\New folder\ZytoTestAutomation\testng.xml
	at org.testng.internal.Parameters.createParams(Parameters.java:290)
	at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:359)
	at org.testng.internal.Parameters.createParameters(Parameters.java:620)
	at org.testng.internal.Parameters.createConfigurationParameters(Parameters.java:190)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:209)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:529)
	at org.testng.TestRunner.run(TestRunner.java:497)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>com.zyto.test.base.ZytoBaseTest@2a4fb17b</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-skipped'>
<tr><td colspan='4' align='center'><b>SKIPPED CONFIGURATIONS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.zyto.test.base.ZytoBaseTest.tearDown()'><b>tearDown</b><br>Test class: com.zyto.test.base.ZytoBaseTest</td>
<td></td>
<td>0</td>
<td>com.zyto.test.base.ZytoBaseTest@2a4fb17b</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_019_Verify__Error_In_Phone_Number_field()'><b>TC_019_Verify__Error_In_Phone_Number_field</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: Verify with InValid Phone number<br/>
<a href="#Output-2114629072" onClick='toggleBox("Output-2114629072", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-2114629072" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-2114629072">
<a href='D:\New folder\ZytoTestAutomation\target\surefire-reports\failure_screenshots\TC_019_Verify__Error_In_Phone_Number_field_26_07_2020_12_30_44.png'> <img src='D:\New folder\ZytoTestAutomation\target\surefire-reports\failure_screenshots\TC_019_Verify__Error_In_Phone_Number_field_26_07_2020_12_30_44.png' height='100' width='100'/> </a><br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: [1;91mError message is   displayed for invalid phone number[0m
	at com.zyto.test.TestCases.Create_profile.TC_019_Verify__Error_In_Phone_Number_field(Create_profile.java:305)
... Removed 26 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace2114629072", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace2114629072'><pre>java.lang.AssertionError: [1;91mError message is   displayed for invalid phone number[0m
	at org.testng.Assert.fail(Assert.java:96)
	at com.zyto.test.TestCases.Create_profile.TC_019_Verify__Error_In_Phone_Number_field(Create_profile.java:305)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>45</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_020_Verify__Error_In_Phone_Number_field()'><b>TC_020_Verify__Error_In_Phone_Number_field</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: Verify with InValid Phone number<br/>
<a href="#Output-1510087865" onClick='toggleBox("Output-1510087865", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-1510087865" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-1510087865">
<a href='D:\New folder\ZytoTestAutomation\target\surefire-reports\failure_screenshots\TC_020_Verify__Error_In_Phone_Number_field_26_07_2020_12_31_55.png'> <img src='D:\New folder\ZytoTestAutomation\target\surefire-reports\failure_screenshots\TC_020_Verify__Error_In_Phone_Number_field_26_07_2020_12_31_55.png' height='100' width='100'/> </a><br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: [1;91mError message is   displayed for invalid phone number[0m
	at com.zyto.test.TestCases.Create_profile.TC_020_Verify__Error_In_Phone_Number_field(Create_profile.java:342)
... Removed 26 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1510087865", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1510087865'><pre>java.lang.AssertionError: [1;91mError message is   displayed for invalid phone number[0m
	at org.testng.Assert.fail(Assert.java:96)
	at com.zyto.test.TestCases.Create_profile.TC_020_Verify__Error_In_Phone_Number_field(Create_profile.java:342)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>44</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_035_Validate_clearing_Errors()'><b>TC_035_Validate_clearing_Errors</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: To validate continue button after clearing errors<br/>
<a href="#Output-9843062" onClick='toggleBox("Output-9843062", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-9843062" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-9843062">
<a href='D:\New folder\ZytoTestAutomation\target\surefire-reports\failure_screenshots\TC_035_Validate_clearing_Errors_26_07_2020_12_47_05.png'> <img src='D:\New folder\ZytoTestAutomation\target\surefire-reports\failure_screenshots\TC_035_Validate_clearing_Errors_26_07_2020_12_47_05.png' height='100' width='100'/> </a><br/>
</div>
</td>
<td><div><pre>org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=83.0.4103.116)
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: &apos;3.14.0&apos;, revision: &apos;aacccce0&apos;, time: &apos;2018-08-02T20:19:58.91Z&apos;
System info: host: &apos;LAPTOP-QBC6F12R&apos;, ip: &apos;192.168.1.102&apos;, os.name: &apos;Windows 10&apos;, os.arch: &apos;amd64&apos;, os.version: &apos;10.0&apos;, java.version: &apos;1.8.0_172&apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 83.0.4103.116, chrome: {chromedriverVersion: 83.0.4103.39 (ccbf011cb2d2b..., userDataDir: C:\Users\Naresh\AppData\Loc...}, goog:chromeOptions: {debuggerAddress: localhost:58851}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: a8350db7f8fe4a5738a89e9592b2fce9
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
	at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:160)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.lambda$new$0(EventFiringWebDriver.java:403)
	at com.sun.proxy.$Proxy25.getText(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.getText(EventFiringWebDriver.java:462)
	at com.zyto.test.TestCases.Create_profile.TC_035_Validate_clearing_Errors(Create_profile.java:867)
... Removed 32 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace9843062", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace9843062'><pre>org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=83.0.4103.116)
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: &apos;3.14.0&apos;, revision: &apos;aacccce0&apos;, time: &apos;2018-08-02T20:19:58.91Z&apos;
System info: host: &apos;LAPTOP-QBC6F12R&apos;, ip: &apos;192.168.1.102&apos;, os.name: &apos;Windows 10&apos;, os.arch: &apos;amd64&apos;, os.version: &apos;10.0&apos;, java.version: &apos;1.8.0_172&apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 83.0.4103.116, chrome: {chromedriverVersion: 83.0.4103.39 (ccbf011cb2d2b..., userDataDir: C:\Users\Naresh\AppData\Loc...}, goog:chromeOptions: {debuggerAddress: localhost:58851}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: a8350db7f8fe4a5738a89e9592b2fce9
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
	at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:160)
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.lambda$new$0(EventFiringWebDriver.java:403)
	at com.sun.proxy.$Proxy25.getText(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.getText(EventFiringWebDriver.java:462)
	at com.zyto.test.TestCases.Create_profile.TC_035_Validate_clearing_Errors(Create_profile.java:867)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>52</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC011_Email_Address_Validation()'><b>TC011_Email_Address_Validation</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: To verify the email address field validation</td>
<td></td>
<td>22</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC012_Existing_Email_Address_Validation()'><b>TC012_Existing_Email_Address_Validation</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: To verify the email address field validation with existing email address</td>
<td></td>
<td>25</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC013_Invalid_Emails_Validation()'><b>TC013_Invalid_Emails_Validation</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: To Verify the filed validation with invalid emails</td>
<td></td>
<td>86</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_010_Verify_First_Last_Name_fields()'><b>TC_010_Verify_First_Last_Name_fields</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: To verify the First and Last Name fields </td>
<td></td>
<td>20</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_014_Verify_Password_field()'><b>TC_014_Verify_Password_field</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: To verify the password field</td>
<td></td>
<td>25</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_015_Verify_Password_field()'><b>TC_015_Verify_Password_field</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: To Verify create password field char limit </td>
<td></td>
<td>25</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_017_Verify_Miscmatch_of_Passwords()'><b>TC_017_Verify_Miscmatch_of_Passwords</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: To verify the error message for mismatch of passwords</td>
<td></td>
<td>30</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_018_Verify__Phone_Number_field()'><b>TC_018_Verify__Phone_Number_field</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: Verify with Valid Phone number</td>
<td></td>
<td>44</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_021_Validate_Mandatory_DOB_Fields()'><b>TC_021_Validate_Mandatory_DOB_Fields</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method:  Enter the DOB fields as mandatory</td>
<td></td>
<td>46</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_022_Validate_Mandatory_DOB_Fields_With_Valid_Date()'><b>TC_022_Validate_Mandatory_DOB_Fields_With_Valid_Date</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method:  Enter the DOB fields as mandatory</td>
<td></td>
<td>25</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_023_Validate_Age_in_Registration()'><b>TC_023_Validate_Age_in_Registration</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method:  Enter the DOB fields as mandatory</td>
<td></td>
<td>45</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_024_Validate_Gender_As_Mandatory_Fields()'><b>TC_024_Validate_Gender_As_Mandatory_Fields</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: Validate the Gender drodpown as mandate</td>
<td></td>
<td>43</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_025_Validate_Gender_Field()'><b>TC_025_Validate_Gender_Field</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: Validate the Gender drodpown as mandate</td>
<td></td>
<td>23</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_026_Validate_Address_Fields()'><b>TC_026_Validate_Address_Fields</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: To validate the Address fields as mandate</td>
<td></td>
<td>33</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_027_Verify_Address_Fields_With_invalid_Data()'><b>TC_027_Verify_Address_Fields_With_invalid_Data</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: To Validate Address fields giving invalid data</td>
<td></td>
<td>33</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_028_Validate_Address_Fields_With_Empty_Data()'><b>TC_028_Validate_Address_Fields_With_Empty_Data</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method:  To Validate the Mailing address fields with empty data</td>
<td></td>
<td>38</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_029_Verify_Country_Field()'><b>TC_029_Verify_Country_Field</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: To Validate Country Field</td>
<td></td>
<td>43</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_030_Validate_State_Province_As_Mandate_Fields()'><b>TC_030_Validate_State_Province_As_Mandate_Fields</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: To Validate State/province  field as mandate</td>
<td></td>
<td>43</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_031_Validate_State_Province_Fields()'><b>TC_031_Validate_State_Province_Fields</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: To Validate State/province  field as mandate</td>
<td></td>
<td>26</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_032_Validate_Post_Code_Field()'><b>TC_032_Validate_Post_Code_Field</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: To Validate Post Code field as mandate</td>
<td></td>
<td>30</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_033_Validate_Continue_Button()'><b>TC_033_Validate_Continue_Button</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: To Validate Continue button</td>
<td></td>
<td>24</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.TC_034_Validate_Errors_On_Clicking_Continue_button()'><b>TC_034_Validate_Errors_On_Clicking_Continue_button</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: To Validate Continue button and  errors</td>
<td></td>
<td>25</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
<tr>
<td title='com.zyto.test.TestCases.Create_profile.Tc_016_Verify_Password_fields_match()'><b>Tc_016_Verify_Password_fields_match</b><br>Test class: com.zyto.test.TestCases.Create_profile<br>Test method: To verify  if Password  and Confirm Password matches</td>
<td></td>
<td>30</td>
<td>com.zyto.test.TestCases.Create_profile@5c6648b0</td></tr>
</table><p>
</body>
</html>